rmb.seo.namespaces.createNamespace("rmb.seo.CookieAfiliados");(function(){var _1=rmb.seo.CookieAfiliados;_whiteLabelData=null;function setWhiteLabelData(_2){_whiteLabelData=_2;};removeOldCookies=function(){var semCookie=getCookie("SEMCOOKIE");var whitelabelCookie=getCookie("AFFILIATES_WHITELABEL");var affiliatedCookie=getCookie("AFILIADO");var actualHostName=location.hostname;var subdomainHostName=actualHostName.indexOf("www")>-1?actualHostName.substring(actualHostName.indexOf(".")):actualHostName;if(!!!semCookie){if(!!whitelabelCookie){delete_cookie("AFFILIATES_WHITELABEL");delete_cookie("AFFILIATES_WHITELABEL",subdomainHostName);guardaCookie("AFFILIATES_WHITELABEL",whitelabelCookie);}
if(!!affiliatedCookie){delete_cookie("AFILIADO");delete_cookie("AFILIADO",subdomainHostName);guardaCookie("AFILIADO",affiliatedCookie);}
guardaCookie("SEMCOOKIE","{\"cookiesDeleted\":\"true\"}");}};delete_cookie=function(name,domain){document.cookie=name+"=;path=/;domain="+(!!domain?domain:"")+";expires=Thu, 01 Jan 1970 00:00:01 GMT";};function checkCookie(){removeOldCookies();var _3="AFILIADO";var _4="AFFILIATES_WHITELABEL";var _5=generateNotWhiteLabelJson("error-affiliate-AFF_ERR_00");var _6=getHost();var _7="google";var _8=document.referrer;var _16="aclk?sa=";var _17="url?sa=";var _z="daf-";var _y="AFFILIATES_DAF";if(_8==null||_8==""){_8="noreferer";}else{_8=formateaAfiliado(_8,_6,_7,_16,_17);}
if(_8==_6){var _9=getCookie(_4);if(_9!=null){_5=_9;}else{_5=generateNotWhiteLabelJson("error-affiliate-AFF_ERR_02");}}else{var _a=rmb_affiliates_gup("org");if(_a==null||_a==""){if(_a==""){_5=generateNotWhiteLabelJson("error-affiliate-AFF_ERR_03");}else{if(_8=="noreferer"){_5=generateNotWhiteLabelJson(_8);}else{_5=generateWhiteLabelJson(_8);}}}else{_5=generateWhiteLabelJson(_a);}}
var _b=eval("("+_5+")");setWhiteLabelData(_b);guardaCookie(_3,_whiteLabelData.affiliateId);guardaCookie(_4,_5);if(_whiteLabelData.affiliateId.indexOf(_z)>-1){guardaDafCookie(_y,_whiteLabelData.affiliateId);}};function guardaCookie(_c,_d){var _e=30;var _f=new Date();_f.setTime(_f.getTime()+(_e*24*60*60*1000));var _10="; expires="+_f.toGMTString();var host=getHost();document.cookie=_c+"="+escape(_d)+_10+";domain="+host+"; path=/";};function guardaDafCookie(_c,_d){var _e=365;var _f=new Date();_f.setTime(_f.getTime()+(_e*24*60*60*1000));var _10="; expires="+_f.toGMTString();var _g=_d;var _h=getCookie(_c);if(_h!=null){if(_h.indexOf(_d)>-1){_g=_h;}else{_g=_h+';'+_d;}}
document.cookie=_c+"="+escape(_g)+_10+"; path=/";};function formateaAfiliado(_11,_12,_13,_18,_19){if(_11!="noreferer"){if(_11.indexOf(_12)>-1){if(_11.indexOf(_18)>-1){_11="Adw";}else{if(_11.indexOf(_19)>-1){_11=_13;}else{_11=_12;}}}else{if(_11.indexOf(_13)>-1){_11=_13;}else{if(_11.indexOf("://")>-1){_11=_11.substring(_11.indexOf("://")+3,_11.length);if((_11.indexOf("/"))>-1){_11=_11.substring(0,_11.indexOf("/"));}}
if(_11.length>38){_11=_11.substring(0,38);}}}}
return _11;};function getCookie(_14){if(document.cookie.length>0){c_start=document.cookie.indexOf(_14+"=");if(c_start!=-1){c_start=c_start+_14.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1){c_end=document.cookie.length;}
return unescape(document.cookie.substring(c_start,c_end));}}
return null;};function rmb_affiliates_gup(_15){_15=_15.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var _16="[\\?&]"+_15+"=([^&#]*)";var _17=new RegExp(_16);var _18=_17.exec(window.location.href);if(_18==null){return null;}else{return _18[1];}};function generateNotWhiteLabelJson(_19){var _1a="{\"isWhiteLabel\":\"false\",\"affiliateId\":\""+_19+"\"}";return _1a;};function generateWhiteLabelJson(_1b){if(_1b.indexOf("www.")==0){_1b=_1b.substr(4);}
var _1c=rmb.seo.WhiteLabelEntries.getWhiteLabelEntry(_1b);if(_1c!=null||_1c!=undefined){ocultar();}else{_1c=generateNotWhiteLabelJson(_1b);}
return _1c;};_1.getWhiteLabelData=function(){return _whiteLabelData;};function ocultar(){var _1d=document.createElement("style");_1d.type="text/css";codigo="#header{display: none;}#footer{display: none;}";if(_1d.styleSheet){_1d.styleSheet.cssText=codigo;}else{_1d.appendChild(document.createTextNode(codigo));}
document.getElementsByTagName("head")[0].appendChild(_1d);};function getHost(){var host=window.location.hostname;var splittedHost=host.split(".");return"."+splittedHost.slice(1,splittedHost.length).join(".");};checkCookie();})();